name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/openclawclient:latest
          ${{ secrets.DOCKER_USERNAME }}/openclawclient:${{ github.ref_name }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/openclawclient:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/openclawclient:buildcache,mode=max

  health-check:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - uses: actions/checkout@v4

    - name: Run health checks
      run: |
        echo "Running health checks..."
        # Add health check scripts here
        echo "Health checks completed"

  deploy-dokploy:
    runs-on: ubuntu-latest
    needs: health-check

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Dokploy
      env:
        DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
        DOKPLOY_BASE_URL: ${{ secrets.DOKPLOY_BASE_URL }}
      run: |
        echo "Deploying to Dokploy..."
        # Add Dokploy deployment commands here
        # Example: curl -X POST $DOKPLOY_BASE_URL/api/deploy \
        #   -H "Authorization: Bearer $DOKPLOY_API_KEY" \
        #   -H "Content-Type: application/json" \
        #   -d '{"projectId":"openclawclient","version":"${{ github.ref_name }}"}'
        echo "Deployment initiated"
